### ISSUE TITLE
GPL-3.0 may not be compatible with GPL-2.0

### ISSUE THREAD

**Issue by andrew** [librariesio/license-compatibility#4]
According to the table on https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses#cite_note-46

It can be compatible with GPL-2.0+ though

**Comment by anseljh** [comment]
Well, here's Section 9 of GPL-2.0 (emphasis added):

> The Free Software Foundation may publish revised and/or new versions of the General Public License from time to time. Such new versions will be similar in spirit to the present version, but may differ in detail to address new problems or concerns.
> 
> Each version is given a distinguishing version number. If the Program specifies a version number of this License which applies to it and "any later version", **you have the option of following the terms and conditions either of that version or of any later version** published by the Free Software Foundation. If the Program does not specify a version number of this License, you may choose any version ever published by the Free Software Foundation.`

**Comment by andrew** [comment]
@anseljh thanks for the pointer, will close this for now then :+1:
