### ISSUE TITLE
CLI tool

### ISSUE THREAD

**Issue by pawamoy** [librariesio/license-compatibility#41]
Would it be possible to have an executable installed in the path when `gem` installing? We would pass a list of licenses (or maybe tuples [package, license]), and it would output conflicts found.

Also interesting resources as of today:

https://choosealicense.com/appendix/
![quick-guide-gplv3-compatibility svg](https://cloud.githubusercontent.com/assets/3999221/22795920/b361a110-eef8-11e6-9d53-7798335503c7.png)
![software-license-compatiblity-graph svg](https://cloud.githubusercontent.com/assets/3999221/22795923/b58090c8-eef8-11e6-8059-55ca4b5d134a.png)
![floss-license-slide-image](https://cloud.githubusercontent.com/assets/3999221/22795926/b817f9f2-eef8-11e6-974c-98b8d1c85a84.png)

**Comment by andrew** [comment]
@Pawamoy sorry for the delay, a CLI sounds like an excellent idea, would you be up for contributing it to the project as a pull request?

**Comment by pawamoy** [comment]
Yes sure, I'll try to find some time and when I'll have something, I'll let you know with a PR :)
